---
name: docker build & test

on:
  - push
  - pull_request

jobs:
  push_to_registry:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
      - name: test
        run: make test
