---
name: hadolint

on:
  - push
  - pull_request

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run hadolint
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: ./Dockerfile
