---
name: make

on:
  - push
  - pull_request

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: make dry-run
        run: make --dry-run --warn-undefined-variables
