---
name: rubocop

on:
  - push
  - pull_request

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Install Rubocop
        run: gem install rubocop
      - name: Check code
        run: rubocop
